# Portainer
version: '3.9'

services:
  # Portainer Server
  server:
    image: docker.io/portainer/portainer-ee:latest
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.rule: Host(`portainer.home.robigan.com`)
      traefik.http.routers.portainer.tls: true
      traefik.http.routers.portainer.tls.certresolver: cfresolver
      traefik.http.services.server-portainer.loadbalancer.server.port: 9000
    restart: unless-stopped
    command:
      - "--log-level=${LOG_LEVEL:-INFO}"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9000:9000
      - 8000:8000
    expose:
      - 9000
    networks:
      - default
      - proxy
      - ldap
#      - portainer
    extra_hosts:
      - "host.docker.internal:host-gateway" # Add host.docker.internal to the container's hosts file, so that it can access the host's network
      - "${OIDC_HOST:-sso.robigan.com}:${OIDC_HOST_ALIAS:-host-gateway}" # Add OIDC host to the container's hosts file, so that it can access the host's network

volumes:
  portainer-data:

networks:
  proxy:
    external: true
    name: proxy
  ldap:
    external: true
    name: ldap
#  portainer:
#    external: true
#    name: portainer-internal
